version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: docs
      args:
        REAL_CPU_BASE_IMAGE: ubuntu:22.04
        REAL_GPU_BASE_IMAGE: nvcr.io/nvidia/pytorch:23.10-py3
    ports:
      - "7780:80"