python -m realhf.apps.quickstart rw \
experiment_name=mistral-tuluSftMixture-tulu2.5-rw \
trial_name=debug \
mode=local \
allocation_mode=manual \
n_nodes=1 \
n_gpus_per_node=8 \
exp_ctrl.total_train_epochs=2 \
exp_ctrl.save_freq_steps=37 \
exp_ctrl.eval_freq_steps=37 \
model.backend=megatron \
model.type._class=mistral \
model.type.is_critic=True \
model.optimizer.lr=0.00001 \
model.optimizer.lr_scheduler_type=linear \
model.optimizer.min_lr_ratio=0.1 \
model.optimizer.warmup_steps_proportion=0.03 \
model.path=/home/zzo/.cache/realhf/checkpoints/root/mistral-tuluSftMixture-sft/debug/default/epoch3epochstep1globalstep4840 \
allocation.n_mbs=4 \
allocation.parallel.pipeline_parallel_size=1 \
allocation.parallel.model_parallel_size=2 \
allocation.parallel.data_parallel_size=4 \
dataset.train_path=/home/zzo/Quickstart/asset/dataset/rw/allenai___tulu-2.5-preference-data/train.json \
dataset.valid_path=/home/zzo/Quickstart/asset/dataset/rw/allenai___tulu-2.5-preference-data/test.json \
dataset.max_pairs_per_prompt=1 \
dataset.max_seqlen=2048 \
dataset.train_bs_n_seqs=512 \
dataset.valid_bs_n_seqs=100
