python -m realhf.apps.quickstart rw \
experiment_name=mistral-mix-saferlhf-rw \
trial_name=debug \
mode=local \
allocation_mode=manual \
n_nodes=1 \
n_gpus_per_node=8 \
exp_ctrl.total_train_epochs=2 \
exp_ctrl.save_freq_steps=72 \
exp_ctrl.eval_freq_steps=72 \
model.backend=megatron \
model.type._class=mistral \
model.type.is_critic=True \
model.optimizer.lr=0.00001 \
model.optimizer.lr_scheduler_type=linear \
model.optimizer.min_lr_ratio=0.1 \
model.optimizer.warmup_steps_proportion=0.03 \
model.path=/mnt/zzo/.cache/realhf/checkpoints/root/mistral-mix-mrsft/debug/default/epoch1epochstep6982globalstep6982 \
allocation.n_mbs=8 \
allocation.parallel.pipeline_parallel_size=1 \
allocation.parallel.model_parallel_size=1 \
allocation.parallel.data_parallel_size=8 \
dataset.train_path=/mnt/zzo/asset/dataset/rw/safe/PKU-Alignment___pku-safe_rlhf/PKU-Alignment___pku-safe_rlhf_default_train.json \
dataset.valid_path=/mnt/zzo/asset/dataset/rw/safe/PKU-Alignment___pku-safe_rlhf/PKU-Alignment___pku-safe_rlhf_default_test.json \
dataset.max_pairs_per_prompt=1 \
dataset.max_seqlen=2048 \
dataset.train_bs_n_seqs=512 \
dataset.valid_bs_n_seqs=64
